import OneNavbar from "@/src/components/header/OneNavbar";
import RootProvider from "@/src/components/providers/RootProvider";
import "@/src/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<RootProvider>
					<OneNavbar />
					{children}
				</RootProvider>
			</body>
		</html>
	);
}
